language: objective-c
before_install:
    - gem install cocoapods -v '0.37.1'
script: xcodebuild -workspace Example/IBDesignable.xcworkspace -scheme IBDesignable-Example -sdk iphonesimulator -destination platform='iOS Simulator',OS=8.1,name='iPhone 5' ONLY_ACTIVE_ARCH=YES clean build
#xcode_workspace: Example/IBDesignable.xcworkspace # path to your xcodeproj folder
#xcode_scheme: IBDesignable-Example
podfile: Example/Podfile
